### ISSUE TITLE
How to use FtpServer in a console application?

### ISSUE THREAD

**Issue by DelphiMan68** [solodyagin/OverbyteICS#2]
Hello Sir,
I want to use FtpServer in console or windows service project. Can you describe steps for this senario?
Thanks for your response

**Comment by fpiette** [comment]
Post your question there: https://en.delphipraxis.net/forum/37-ics-internet-component-suite/
And use the latest ICS version available from http://wiki.overbyte.eu/wiki/index.php/ICS_Download
To start, look at the console mode demos. There is no difference about how you develop a console mode application with any ICS component. Of course the details about a given component is specific.
